version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "app-cicd"
s3_bucket = "aws-sam-cli"
s3_prefix = "app-cicd"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = false
image_repositories = []
